version: '3.7'
services:
  bot:
    build: .
    volumes:
      &bot-volumes
      - .:/bot
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    depends_on:
      - db
    environment:
      &bot-environment
      TZ: "Europe/Moscow"
      REDIS_URL: redis://redis
    tty: true
    # command: exe/app
    command: bundle exec ruby /bot/app/application.rb && bundle exec ruby /bot/scheduler.rb
    env_file:
      - .env
    restart: on-failure
  db:
    image: postgres:12.0-alpine
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ="Europe/Moscow"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
  sidekiq:
    build: .
    # command: bundle exec sidekiq -r /bot/config/initializers/sidekiq.rb
    command: bash -c "bundle exec sidekiq -r ./app/workers/load_workers.rb"
    depends_on:
      - redis
      - db
    # volumes:
    #   - .:/bot
    #   - redis
    #   - db
    env_file:
      - .env
    environment: *bot-environment
    volumes: *bot-volumes
volumes:
  bundle_cache:
  postgres_data:
