version: '3.7'
services:
  bot:
    build: .
    volumes:
      - .:/bot
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    depends_on:
      - db
    environment:
      TZ: "Europe/Moscow"
    tty: true
    command: exe/app
  db:
    image: postgres:12.0-alpine
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ="Europe/Moscow"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  bundle_cache:
  postgres_data:
